name: CI

on:
  push:
    tags:
      - 'v*'

jobs:
  publish_github:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: change package name
        uses: deef0000dragon1/json-edit-action@v1
        env:
          KEY: name
          VALUE: "@wxsms/vuepress-theme-mini"
          FILE: package.json
      - uses: c-hive/gha-yarn-cache@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: yarn --frozen-lockfile
      - uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          registry: https://npm.pkg.github.com/
          check-version: false
